# 1. Định danh service và cổng chạy
spring.application.name=job-service
server.port=8082
# 2. Cấu hình kết nối PostgreSQL
# Lưu ý: Thay tên database (techcareer_db), username và password theo đúng tài khoản PostgreSQL trên máy của bạn
spring.datasource.url=jdbc:postgresql://localhost:5432/job-service?currentSchema=job_service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# 3. Cấu hình JPA / Hibernate
# ddl-auto=none: Không tự tạo bảng vì ta đã quản lý qua file job-schema.sql
spring.jpa.hibernate.ddl-auto=none
# 4. Hiển thị câu lệnh SQL trong Console khi chạy (giúp debug cực kỳ dễ)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true